Add SASA mdakit to register
MDAnalysis/MDAKits pull request #100
Opened 2023-11-21 18:16 UTC by pegerto

Include basic SASA calculator for total surface and per-residue surface, with standard parameter approximation.

2023-11-28 19:44 UTC, pegerto commented
hi @IAlibay  

Thanks for the update, no problem, this is not urgent.

2023-12-12 08:36 UTC, IAlibay commented
@MDAnalysis/mdakits-reviewers could someone take on the first round of review here - especially pinging @fiona-naughton

2023-12-20 11:11 UTC, pegerto commented
hi @fiona-naughton @MDAnalysis/mdakits-reviewers, any progress on this one, regards.

2023-12-24 15:46 UTC, IAlibay requested changes
Apologies for the delay @pegerto

I've added a few comments that would be nice to address before merging. The only thing I would encourage / block on, is adding the extra references for FreeSASA if possible.

2023-12-24 15:46 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +    This MDAKit allows enables the calculation of Solvant Accessible Surface Area ( SASA) with MDAnalysis.
Would it be worth precising that this is done via FreeSASA or do you have plans to expand beyond this?

2023-12-24 15:46 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +  - FreeSasa
```suggestion
  - SASA
  - FreeSASA
```
Small gramatical thing

2023-12-24 15:46 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +documentation_type: UserGuide + API
Note: We don't have a policy to take a stance here.

Looking at your docs it looks mostly API, there's not that much, if at all, "userguide", is this label for the documentation type intented?

2023-12-24 15:46 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +  - https://zenodo.org/doi/10.5281/zenodo.10182425
Could you add relevant publications for FreeSASA too please? This would be a nice addition to recognise the upstream work. You can find relevant citation information here: https://freesasa.github.io/

2023-12-24 17:02 UTC, pegerto commented on mdakits/sasa/metadata.yaml
> +    This MDAKit allows enables the calculation of Solvant Accessible Surface Area ( SASA) with MDAnalysis.
No plan to extend beyond FreeSASA I will clarify the use of FreeSASA on the description field.

2023-12-24 17:08 UTC, pegerto commented on mdakits/sasa/metadata.yaml
> +documentation_type: UserGuide + API
Agree on this one, I added the following https://github.com/pegerto/mdakit_sasa/issues/20

Will work on this one this week.

2023-12-24 17:17 UTC, pegerto commented on mdakits/sasa/metadata.yaml
> +    This MDAKit allows enables the calculation of Solvant Accessible Surface Area ( SASA) with MDAnalysis.
done

2023-12-24 17:20 UTC, pegerto commented on mdakits/sasa/metadata.yaml
> +  - https://zenodo.org/doi/10.5281/zenodo.10182425
There are reference to FreeSASA in the documentation but completely agree need to be described here.

2023-12-24 17:21 UTC, pegerto commented on mdakits/sasa/metadata.yaml
> +  - https://zenodo.org/doi/10.5281/zenodo.10182425
thank you for potting it out

2023-12-24 17:27 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +  - https://zenodo.org/doi/10.5281/zenodo.10182425
Thanks!

2023-12-24 17:27 UTC, IAlibay commented on mdakits/sasa/metadata.yaml
> +documentation_type: UserGuide + API
Awesome :)

2023-12-24 17:27 UTC, IAlibay approved these changes
This looks great, thanks so much for submitting this @pegerto !

2023-12-24 18:00 UTC, merged