Add guide for reviewers
MDAnalysis/MDAKits pull request #119
Opened 2024-01-17 15:56 UTC by fiona-naughton

Added a guide aimed at people reviewing kits (issue #103). 

This is fairly bare-bones formatting at the moment – I might keep playing around with potential ways to smarten it up, but this will at least give people a chance to review the text. I’ve tried not to assume too much knowledge from the reviewer’s side, with the idea we might get people in the broader community involved.

Also played around with the contents grouping/home page a little while here, to try get more focus on the registry itself - towards #34

2024-01-20 07:17 UTC, IAlibay requested changes
This looks great, thanks @fiona-naughton !

Just putting a requested changes down because it looks like the front page no longer links to the registry anymore.

2024-01-20 07:17 UTC, IAlibay commented on docs/source/index.rst
>     mdakits
I like the re-org here, but this link isn't showing up anymore :(

2024-01-20 07:17 UTC, IAlibay commented on docs/source/reviewersguide.rst
> +  - If the Kits’ tests use `tox`, these need to be manually checked
Do we need to include a "why" here? I.e. that tox can make tests look like they pass even when they don't?

2024-01-20 07:17 UTC, IAlibay commented on docs/source/reviewersguide.rst
> +  - A failure on installing dependencies may be due the things in the Kit’s `pyproject.toml` not
```suggestion
  - A failure on installing dependencies may be due the entires in the Kit’s `pyproject.toml` not
```
This is very nitpicky 😅

2024-01-20 07:23 UTC, fiona-naughton commented on docs/source/index.rst
>     mdakits
ah yes, thanks - that'll be because it's "hidden" atm, I was playing around with embedding the table directly instead but it wasn't quite working, I can revert that

2024-01-20 07:25 UTC, fiona-naughton commented on docs/source/reviewersguide.rst
> +  - If the Kits’ tests use `tox`, these need to be manually checked
sound good! I had meant to ask you about this actually, since I'm not familiar with tox myself - would a manual check in this case just mean looking through the details link rather than trusting what github says in the PR?

2024-01-20 07:42 UTC, fiona-naughton commented on docs/source/reviewersguide.rst
> +  recommended* here to provide this metadata.
Just to note here - whether to make tests (and installation instructions) mandatory rather than optional is currently an open issue (see #95  and #98 ) - I'll restart the discussion there, but it's likely we won't reach a consensus before this PR is merged, so I'll keep them here as optional for now.

2024-01-20 18:33 UTC, IAlibay commented on docs/source/reviewersguide.rst
> +  - A failure on installing dependencies may be due the entires in the Kit’s `pyproject.toml` not
```suggestion
  - A failure on installing dependencies may be due the entries in the Kit’s `pyproject.toml` not
```
Looks like I can spell 🤦🏽

2024-01-20 18:34 UTC, IAlibay commented on docs/source/reviewersguide.rst
> +  recommended* here to provide this metadata.
Agreed, let's prioritize merging this even if we don't come to a conclusion on that discussion (which seems to have stalled quite a bit).

2024-01-22 09:51 UTC, IAlibay approved these changes
I'll unblock since the one thing I wanted has been addressed - that being said this guide isn't really for me. @lilyminium @orbeckst may I ask for at least one of you to have a look?

2024-01-22 10:02 UTC, fiona-naughton commented on docs/source/reviewersguide.rst
> +you’d like to be involved with reviewing MDAKit submissions.
It'd probably be helpful to more specifically direct people here - not sure if we wanted to just name the usual suspects, of if we have specific MDAKits points-of-contact?

2024-01-22 20:48 UTC, orbeckst commented on docs/source/reviewersguide.rst
> +you’d like to be involved with reviewing MDAKit submissions.
Perhaps point to the MDAkits forum and tell them to use a team-at handle for MDAKits ... if we don't have one, we should make one.

2024-01-22 20:59 UTC, orbeckst approved these changes
Nice work @fiona-naughton . I did a quick read through. Minor comments inline. Can certainly be merged and if there's anything that I overlooked we can fix iteratively.

2024-01-22 20:59 UTC, orbeckst commented on docs/source/index.rst
> +==================================
Is this a heading or using the style of a heading? If the latter, I'd prefer to bold-face and explicitly style and not abuse semantic markup. If it's meant as a heading then it's fine.

2024-01-22 20:59 UTC, orbeckst commented on docs/source/index.rst
> +.. _`MDAKit registry`: https://mdakits.mdanalysis.org/mdakits.html
In restructured text, used ref and labels instead of hyper links when it's a link inside the docs.

2024-01-22 20:59 UTC, orbeckst commented on docs/source/reviewersguide.rst
> +github repository, consisting of a single `metadata.yaml` file (or one per Kit, if multiple Kits are
Double back-tics in reST.

2024-01-22 20:59 UTC, orbeckst commented on docs/source/reviewersguide.rst
> +  the `metadata.yaml` file) with the latest and/or develop versions of MDAnalysis
```suggestion
  the ``metadata.yaml`` file) with the latest and/or develop versions of MDAnalysis
```

2024-01-22 20:59 UTC, orbeckst commented on docs/source/reviewersguide.rst
> +  View the page generated by `readthedocs` (by clicking *Details* next to the check) and find the
NOt sure what markup to be used on readthedocs. Perhaps just not markup or emphasized?
```suggestion
  View the page generated by *readthedocs* (by clicking *Details* next to the check) and find the 
```

2024-01-22 20:59 UTC, orbeckst commented on docs/source/reviewersguide.rst
> +|
What does the pipe character do here??

2024-01-30 19:01 UTC, fiona-naughton commented on docs/source/index.rst
> +==================================
I was abusing the markup in order to make it larger font-size 😅 largely since I think it helps this stand out better - there might be a better way to do that

2024-03-27 23:54 UTC, orbeckst commented
Thank you! All lgtm... please merge!!

2024-03-27 23:54 UTC, orbeckst approved these changes
LGTM! please merge

2024-05-24 19:19 UTC, merged