Register spyrmsdkit
MDAnalysis/MDAKits pull request #146
Opened 2024-05-31 20:42 UTC by RMeli

MDAKit to run [spyrmsd](https://github.com/RMeli/spyrmsd) (symmetry-corrected RMSD) on MD trajectories.

2024-05-31 22:18 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +  - pip install spyrmsdkit
```suggestion
#install:
#  - pip install spyrmsdkit
```

2024-06-24 06:34 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +#  - pip install spyrmsdkit
Is there not a compatible release?

2024-06-24 07:10 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +#  - pip install spyrmsdkit
Not yet. Is that mandatory?

2024-06-24 07:18 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +#  - pip install spyrmsdkit
Not mandatory but generally encouraged, especially if it'll happen soon - saves having to chase up an update to the metadata file later

2024-06-24 07:41 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +#  - pip install spyrmsdkit
I'm not sure if it will happen soon. I'd like to collect more feedback from actual users before (hence why I was going for the MDAKit Registry before doing a full release).

2024-06-28 01:31 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +#  - pip install spyrmsdkit
That's fair, please remember to update later then !

2024-06-28 01:32 UTC, IAlibay approved these changes

2024-06-28 01:33 UTC, IAlibay requested changes

2024-06-28 01:33 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +project_home: https://github.com/RMeli/MYPROJECT/
o actually this is using the template?

2024-06-28 01:34 UTC, IAlibay approved these changes

2024-06-28 01:34 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +license: GPL-2.0-or-later
just FYI that probably should be 3+ since MDA is currently packaged as 3+

2024-06-28 01:34 UTC, IAlibay requested changes
sorry I'm on my phone and I keep clicking the wrong things - block on the template path not approve

2024-06-28 06:47 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +project_home: https://github.com/RMeli/MYPROJECT/
```suggestion
project_home: https://github.com/RMeli/spyrmsdkit/
```
Ooof. Good catch!

2024-06-28 06:50 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +license: GPL-2.0-or-later
This is the actual licence used by the MDAKit. This doesn't appear to have changed in the `cookiecutter-mdakit`. Should this be changed everywhere (including the cookie cutter)? I can do that if needed.

2024-07-07 02:08 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +license: GPL-2.0-or-later
Erm, yeah this is mostly a temporary thing, in the end the package will just be 3+ for now and then will turn 2+ once we drop the Apache licenses. It's not a hill I care to spend too much time on.

2024-07-07 02:10 UTC, IAlibay approved these changes

2024-07-07 02:10 UTC, merged

2024-07-08 07:24 UTC, RMeli commented on mdakits/spyrmsdkit/metadata.yaml
> +license: GPL-2.0-or-later
Ok, thanks for the clarification. I was asking just to get a better understanding of the MDAKit side of things.

2024-07-08 14:03 UTC, IAlibay commented on mdakits/spyrmsdkit/metadata.yaml
> +license: GPL-2.0-or-later
It's a perfectly good question tbh and we should probably fix it, but also time is probably best spent elsewhere.