add lipidorderkit to mdanalysis
MDAnalysis/MDAKits pull request #149
Opened 2024-06-28 21:46 UTC by ricard1997

This code allows for the computation of lipid order parameters for all-atom MDAsimulation for researchers that study membrane simulations.

2024-07-06 19:04 UTC, lilyminium requested changes
Hi @ricard1997, thanks for adding your MDAKit to the registry -- exciting to see more lipid analyses here! I've just done a quick first pass over the metadata file and commented on where some entries need some modification to be properly parsed by the MDAKits registry.

2024-07-06 19:04 UTC, lilyminium commented on mdakits/lipidorderkit/metadata.yaml
> +  - pip install git+https://github.com/ricard1997/lipidorderkit@main
```suggestion
  - git clone https://github.com/ricard1997/lipidorderkit.git
  - cd lipidorderkit && pip install . && cd ..
```

These commands clone the repo and then install the package from source.

2024-07-06 22:25 UTC, ricard1997 commented on mdakits/lipidorderkit/metadata.yaml
> +documentation_type: UserGuide + API
Yes, once the MDAKit is accepted I plan to do a full tutorial and an explanation about lipid order parameters.

2024-07-06 23:00 UTC, ricard1997 commented on mdakits/lipidorderkit/metadata.yaml
> +# MYPACKAGE is how you import it in python.
Thanks for the feedback! I have added all the commits and remove explanatory comments, let me know if there is something else to be done.

2024-07-07 01:58 UTC, IAlibay commented
CI is failing due to a typo - I opened a PR in the mdakit to fix this.

2024-07-08 13:04 UTC, ricard1997 commented
> CI is failing due to a typo - I opened a PR in the mdakit to fix this.

I have accepted the PR. Let me know if something else is needed.

2024-07-09 12:29 UTC, lilyminium commented on mdakits/lipidorderkit/metadata.yaml
> +documentation_type: UserGuide + API
I see, thanks for the update! Just to check -- @IAlibay is having future plans ok for the initial metadata file, or is it better to just say there's API docs here first and then open a new PR to update `metadata.yaml` once a user guide exists?

2024-07-09 12:32 UTC, lilyminium commented
Thanks for updating the file @ricard1997! All looking pretty good -- however I think CI is failing due to not finding test files, which I hopefully fixed in https://github.com/ricard1997/lipidorderkit/pull/3.

2024-07-09 17:32 UTC, ricard1997 commented
> Thanks for updating the file @ricard1997! All looking pretty good -- however I think CI is failing due to not finding test files, which I hopefully fixed in [ricard1997/lipidorderkit#3](https://github.com/ricard1997/lipidorderkit/pull/3).

Thanks for the help with the problem with pytest!
I have solved the problem with the CI, and think everything is finally ready. Thanks for the feedback!

2024-07-11 06:44 UTC, lilyminium commented on mdakits/lipidorderkit/metadata.yaml
> +documentation_type: UserGuide + API
@IAlibay just pinging on this again

2024-07-11 16:11 UTC, IAlibay commented on mdakits/lipidorderkit/metadata.yaml
> +documentation_type: UserGuide + API
Thanks for the ping @lilyminium - I saw the ping in my notifications but somehow not the comment

My recommendation would be to stick with API for now @ricard1997. I realise it's extra hoops, but it is best to be honest with users early on so you don't raise their expectations if they were to try to use/look at your code today.

That being said, if you really want to state it has a userguide, then the review process is not meant to be blocking so we won't halt over it.

2024-07-12 15:09 UTC, ricard1997 commented on mdakits/lipidorderkit/metadata.yaml
> +documentation_type: UserGuide + API
That makes sense. I have add a commit updating the documentation type. I'll soon add the user guide and do another commit on that. Thanks for the feedback!

2024-07-17 08:40 UTC, lilyminium approved these changes
All LGTM -- thank you for making the changes @ricard1997!! Very happy to see a new lipid kit in the registry.

2024-07-17 08:41 UTC, merged