Add MDANCE to MDAnalysis
MDAnalysis/MDAKits pull request #155
Opened 2024-07-11 01:53 UTC by lexin-chen

Hi MDAnalysis team!

Hope this message finds you well. MDANCE is a flexible n-ary clustering algorithm for Molecular Dynamics trajectories. We currently have a fully deterministic k-means clustering (NANI) included a pipeline for determining the number of clusters in the system, ways to identify better cluster representatives, etc. We will be adding more clustering algorithms to this package after publishing them. In conversations with @orbeckst , he suggested that we should try to incorporate this project as an MDAkit, so we are looking forward to collaborating with you.

Best,
Lexin

2024-07-11 02:08 UTC, orbeckst commented
Hi @lexin-chen , great to see your MDANCE package here! I'll start reviewing and may ask others from the team for help.

2024-07-11 02:15 UTC, orbeckst commented
I am following the [MDAKits reviewer guide](https://mdakits.mdanalysis.org/reviewersguide.html)

## Checklist
### PR
- [ ] Are the automatic checks all passing?
- [ ] Did the docs build correctly?
- [ ] Is the metadata file named correctly and in the right location?

### MDAKit home
- [ ] link ok?
- [ ] summary?
- [ ] docs?
- [ ] installation instructions?
- [ ] license?

### Metadata file
Required entries
- [ ] project_name
- [ ] authors
- [ ] maintainers
- [ ] description
- [ ] keywords
- [ ] licence (really, we are using British spelling?!)
- [ ] project_home
- [ ] documentation_home
- [ ] documentation_type

Optional entries but required in practice
- [ ] install, src_install, import_name, python_requires: all automatically checked, ok when CI is green
- [ ] run_tests: automatic but sanity check
- [ ] mdanalysis_requires: manually double check

Optional entries
- [ ] development_status
- [ ] publications
- [ ] changelog

2024-07-11 03:01 UTC, orbeckst commented
Just to add to my review: We are not looking for complete tests of everything. This is hard to do. Instead we'd like to see a few tests that run some of your typical functions. This is typically something that you are already doing in the examples. You then add an appprpriate `assert` statement at the end of the test function to assert that the test output is the same as a correct answer that you stored in the tests.

2024-07-11 03:04 UTC, orbeckst commented
Also, even though I included gridDataFormats as a real-live example of testing, you might be better off just looking at https://github.com/MDAnalysis/mdgeomkit/tree/main/mdgeom/tests, which uses no outdated constructs... when I started my review I only thought about mdgeomkit half-way through writing...

2024-07-12 00:40 UTC, lexin-chen commented
Thanks @orbeckst for the comprehensive comments! I'll definitely look into the tests and add support for this soon!

2024-07-30 00:18 UTC, orbeckst commented
Hi @lexin-chen , do you need help with anything? It would be great to have the package registered before the UGM!

2024-07-31 02:09 UTC, lexin-chen commented
Thanks for checking up with me. I have written some tests on the tools and inputs folder. Once I work on the tests for nani I will submit it prob by the beginning of next week! Sorry about that, since I am not doing research full-time this summer, things have slowed down a bit.

2024-07-31 18:18 UTC, orbeckst requested changes
Great that you added tests. I haven't had time to install mdance and try the tests locally. I think there are different changes to be made in the file so that tests can run. You should be able to just accept the changes so that can we see if it works.

2024-07-31 18:18 UTC, orbeckst commented on mdakits/mdance/metadata.yaml
> +#run_tests:
need to enable the item and give commands to get the source code
```suggestion
run_tests:
  - git clone latest
```
Let's try this.

2024-07-31 18:18 UTC, orbeckst commented on mdakits/mdance/metadata.yaml
> +#  - mamba install pytest MDAnalysisTests
We also need to install pytest because it's not listed in the dependencies https://github.com/mqcomplab/MDANCE/blob/9791f82a872b2f677f44391cf2998b4a2c143005/pyproject.toml#L19-L25 that are installed with the `src_install:` commands.
```suggestion
test_dependencies:
  - pip install pytest
```

2024-08-01 19:37 UTC, orbeckst requested changes
Excellent that you added tests. I also tried them locally and they are clearly working. ✅ 

The one current failure in the workflow is not a real show-stopper but it would be easy to fix: Add a tag for your releases in GitHub; the easiest way to do this is to create an initial release in https://github.com/mqcomplab/MDANCE/releases . This is needed so that we can identify your latest released version of the code. You should run the command
```
git describe --tags `git rev-list --tags --max-count=1`
```
and it should return something like `v0.2.5` or `0.2.5`. 

At the moment it does not find anything and reports the error _fatal: No names found, cannot describe anything._

If you don't want to add tags at the moment then let me know and I will approve. Just know that this will probably lead to some red "failing" badges.


Btw, I see that you're defining the version in your pyproject.toml. We found it extremely convenient to define the version through the tag itself and then use [versioningit](https://versioningit.readthedocs.io/en/stable/index.html) to include the version from the tag into the package. In this way, there's exactly one place where the version is defined.

2024-08-01 19:46 UTC, orbeckst commented on mdakits/mdance/metadata.yaml
> +  - pytest ./tests
Try out the following
```suggestion
  - pytest --pyargs mdance
```
This might make it work without having to tag the releases. (Tagging would still be a good idea but it's not 100% necessary.)

2024-08-01 19:46 UTC, orbeckst commented on mdakits/mdance/metadata.yaml
> +  - pytest ./tests
I am trying this out to see if CI passes.

2024-08-01 19:53 UTC, orbeckst commented on mdakits/mdance/metadata.yaml
> +  - pytest ./tests
This didn't work because the tests are not part of the package. I am reverting the change. You'll need to add the tag to make it work.

2024-08-02 18:18 UTC, lexin-chen commented
Hi @orbeckst , thanks for the great suggestions! as per your advice, I did create tags and release and now I have dynamic versioning as part of the package. Is there a way to recheck for the GitHub actions since I have no changes to the metadata file?

2024-08-02 20:57 UTC, orbeckst commented
Excellent!

I just restarted the failed job — I can do this through the GH actions interface.

2024-08-02 21:25 UTC, orbeckst approved these changes
@lexin-chen this is all looking excellent. Thank you so much for working with me and really taking my suggestions on board.

I will merge this PR and then MDANCE is officially registered! Congratulations 🎉 !

2024-08-02 21:30 UTC, merged

2024-08-02 21:30 UTC, orbeckst commented
MDANCE is officially registered!

2024-08-02 21:32 UTC, lexin-chen commented
Thanks so much for your help and tips @orbeckst! I learned a lot from this experience too. Very glad it worked out