Adding pytim
MDAnalysis/MDAKits pull request #158
Opened 2024-08-06 09:41 UTC by Marcello-Sega

2024-08-06 21:48 UTC, orbeckst requested changes
Thank you for submitting pytim. Looks very good.

I have to required, minor fixes (see comments) and one question where I need some input from @IAlibay about changes in the installed environment.

2024-08-06 21:48 UTC, orbeckst commented on mdakits/pytim/metadata.yaml
> +development_status: Production/Stable
Pleas fix: The correct classifier is `Development Status :: 5 - Production/Stable`

2024-08-06 21:48 UTC, orbeckst commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
I think it would be cleaner if the `pip install` were under `test_dependencies` or did that not work?

2024-08-06 21:48 UTC, orbeckst commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
Are mdtraj, gsd, PyWavelets, scikit-image optional dependencies that are not automatically installed with `pip install pytim`?

Also, is the restriction on `gsd<=3.2.1` necessary? (MDAnalysis itself requires `gsd>3.0.0` so we should be able to install a version that works for both packages but having less restrictive version requirements would be better for future compatibility.)

2024-08-06 21:48 UTC, orbeckst commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
This `pip install` replaces numpy 2.0.1 with numpy 1.26 – probably because of one of the dependencies. pytim itself has `numpy>=1.16.0` in https://github.com/Marcello-Sega/pytim/blob/master/requirements.txt . Is this an problem @IAlibay ?

2024-08-06 22:04 UTC, Marcello-Sega commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
I'll try to clean up this part. I'm also updating the dependencies in another minor update of pytim, removing python2.8 support and requiring MDAnalysis>=2.7 & numpy>=1.22.3. All is good with the GitHub workflows, but CircleCI (both on GitHub and on coda-forge) is giving me a headache – some tests are returning different numbers and it's not about truncation, it really looks like some methods are behaving differently, but I can't find out which ones, or what is different betwee GitHub workflows and CircleCI.

Bottom line, it might take a bit, sorrry :(

2024-08-06 22:10 UTC, Marcello-Sega commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
About numpy 2.0.x, I see that `mdanalysis 2.7.0 requires numpy<2.0,>=1.22.3,`

2024-08-07 12:17 UTC, Marcello-Sega commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
Re. numpy 2, more specifically:

```
pip install --user --upgrade "numpy>2.0.0" "MDAnalysis>=2.7.0"

Collecting numpy>2.0.0
  Using cached numpy-2.0.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: MDAnalysis>=2.7.0 in /Users/marcello/Library/Python/3.9/lib/python/site-packages (2.7.0)
INFO: pip is looking at multiple versions of mdanalysis to determine which version is compatible with other requirements. This could take a while.
Collecting MDAnalysis>=2.7.0
  Using cached MDAnalysis-2.7.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (46 kB)
ERROR: Cannot install mdanalysis==2.7.0 and numpy>2.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy>2.0.0
    mdanalysis 2.7.0 depends on numpy<2.0 and >=1.22.3
    The user requested numpy>2.0.0
    mdanalysis 2.7.0 depends on numpy<2.0 and >=1.22.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

2024-08-14 01:04 UTC, orbeckst commented on mdakits/pytim/metadata.yaml
> +  - pip install "mdtraj" "codecov==2.1.13" "pytest-cov==5.0.0" "cython>=0.24.1"  "scipy>=1.6.0" "gsd<=3.2.1" "PyWavelets>=0.5.2" "scikit-image>=0.14.2" "sphinx>=1.4.3" "matplotlib" "dask>=1.1.1"
You're right @Marcello-Sega — I had at the back of my head "we're supporting numpy 2" ... but that's in develop not in 2.7.0.

2024-08-14 01:11 UTC, orbeckst approved these changes
All looks good to me, thank you for making the effort to register pytim. I am approving the registration. 🎉

2024-08-14 01:11 UTC, merged