Add openmmdl as MDAKit
MDAnalysis/MDAKits pull request #161
Opened 2024-08-23 11:41 UTC by talagayev

Addition of `OpenMMDL` to `MDAKits`:

Package for Interface to OpenMM for easy setup of molecular dynamic simulations of protein-ligand complexes and the analysis thereof, available at:

https://anaconda.org/conda-forge/openmmdl

2024-08-29 15:42 UTC, orbeckst requested changes
The main issue is that one set of tests for py 3.12 fails with an installation issue for mdtraj
```

Could not solve for environment specs
The following package could not be installed
└─ openmmdl is installable and it requires
   └─ mdtraj 1.9.7.*  with the potential options
      ├─ mdtraj 1.9.7 would require
      │  └─ python >=3.10,<3.11.0a0 , which can be installed;
      ├─ mdtraj 1.9.7 would require
      │  └─ python >=3.11,<3.12.0a0 , which can be installed;
      ├─ mdtraj 1.9.7 would require
      │  └─ python >=3.7,<3.8.0a0 , which can be installed;
      ├─ mdtraj 1.9.7 would require
      │  └─ python >=3.8,<3.9.0a0 , which can be installed;
      └─ mdtraj 1.9.7 would require
         └─ python >=3.9,<3.10.0a0 , which can be installed.
```
I am not really sure what's going on so I am bouncing this back to you to look into and report back... 

UPDATE: Looking more closely into the ["develop" test run](https://github.com/MDAnalysis/MDAKits/actions/runs/10525088138/job/29374656029?pr=161#step:7:8), which supposedly passed, I can now see that this run did not actually install the package:
```

Run if [[ develop == "develop" ]]; then
  if [[ develop == "develop" ]]; then
    type="src"
  else
    type="install"
  fi
  
  install=$(python utils/get_install.py --itype ${type} --mdakit openmmdl)
  echo "install=${install}"
  eval ${install}
  shell: /usr/bin/bash -l {0}
  env:
    PYVER: 
    INPUT_RUN_POST: true
    CONDA: /usr/share/miniconda3
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
install=
```
Similarly, the "run tests" also come back empty and report success
```
Run tests=$(python utils/get_runtests.py --mdakit openmmdl --runtype develop)
  tests=$(python utils/get_runtests.py --mdakit openmmdl --runtype develop)
  echo "tests: ${tests}"
  eval ${tests}
  shell: /usr/bin/bash -l {0}
  env:
    PYVER: 
    INPUT_RUN_POST: true
    CONDA: /usr/share/miniconda3
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
tests: 
```

This means that you also need instructions how to install from source (and my hunch is that the testing command that I already mentioned also needs updating).

2024-08-29 15:42 UTC, orbeckst commented on mdakits/openmmdl/metadata.yaml
> +## Here we use a simple PyPi installation:
would remove the comment line, given that you use mamba ;-)

2024-08-29 15:42 UTC, orbeckst commented on mdakits/openmmdl/metadata.yaml
> +  - pytest openmmdl/
Does this work with the conda-forge package? I'd assume you'd first need to get the sources with something like `git clone latest` or similar (see docs).

2024-08-29 17:48 UTC, talagayev commented
@orbeckst hey Oliver,

Hm I can take a look into mdtraj to adjust the `mdtraj` version, since the code mainly uses `mdtraj` only for one function, which ist `image_molecules()`, else I can just replace it with an `mdanalysis` function to do the same :)

2024-08-29 18:54 UTC, talagayev commented
Ah `ambertools` also complains about the imcompatability with the `python` version, so that currently only `python 3.10` is the python version covering all of the packages. I will then update the packages and test them to be compatible with `python 3.11` and `python 3.12`, make a release and get then the compatable release version on `conda-forge` so that it works with all 3 python versions.

2024-08-29 19:06 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +## Here we use a simple PyPi installation:
True, removed them :)

2024-08-29 19:08 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +  - pytest openmmdl/
Yes, added the `git clone latest` line :)
Yes works, but only for `python 3.10`, for the other python versions I will then check the versions of the packages.

2024-09-01 08:37 UTC, IAlibay commented
@lilyminium @fiona-naughton can either of you assign yourselves to shepherd this PR?

2024-09-03 22:29 UTC, orbeckst requested changes
✅ The *openmmmdl (latest)* installs and runs the tests successfully.
❌ The *openmmmdl (develop)* does not properly install, see e.g. https://github.com/MDAnalysis/MDAKits/actions/runs/10688427502/job/29628268563?pr=161#step:7:18 — the following steps all complete seemingly successfully 

The develop tests should also run properly with an installed version of the software.

2024-09-03 22:38 UTC, talagayev commented
@orbeckst If I understand correctly the tests are successfull with the latest version of mdanalysis, but errors appear with the devlopment version of mdanalysis, so I can check if they run locally by using the development mdanalysis package locally and looking if it installs and runs the tests successuflly?

2024-09-03 22:48 UTC, orbeckst commented
When you look at the GH actions report at the line that I linked, you see that
```
install=$(python utils/get_install.py --itype ${type} --mdakit openmmdl)
```
gives an empty `install` variable. 

I would assume that this is because there's an issue with the metadata.yml file and [utils/get_install.py](https://github.com/MDAnalysis/MDAKits/blob/main/utils/get_install.py) is getting confused somehow. That's where I would start.

2024-09-03 22:54 UTC, IAlibay requested changes
Apologies folks, I haven't been keeping up with this.

Looks like the develop failure is because there's a missing `src_install` entry, which is a requirement for mdakit registration.

2024-09-03 23:30 UTC, talagayev commented
@IAlibay hm shouldn't be a problem to add the `src_install` entry, the only problem is that I would not be able to have all of the packages being installable with `pip` due to using `plip` for protein-ligand interaction analysis, which uses `openbabel` that has the problem with the wheel building, so the installation with pip would miss this package. I will then add the `src_install` entry now :)

2024-09-03 23:36 UTC, talagayev commented
I added the `src_install` entry and will then move the packages that are possible to be installed with `pip` tomorrow to the `pyproject.toml` in the `OpenMMDL` repository, with the exception of `plip`, thanks @IAlibay  for helping with the PR:)

2024-09-03 23:40 UTC, IAlibay commented
> @IAlibay hm shouldn't be a problem to add the `src_install` entry, the only problem is that I would not be able to have all of the packages being installable with `pip` due to using `plip` for protein-ligand interaction analysis, which uses `openbabel` that has the problem with the wheel building, so the installation with pip would miss this package. I will then add the `src_install` entry now :) 

You can have a separate mamba install call before the pip install, i.e. it's a list so you can just add more things as necessary - I believe a few other mdakits do this (I'll try to find an example later if I get a chance)

2024-09-03 23:50 UTC, talagayev commented
> > @IAlibay hm shouldn't be a problem to add the `src_install` entry, the only problem is that I would not be able to have all of the packages being installable with `pip` due to using `plip` for protein-ligand interaction analysis, which uses `openbabel` that has the problem with the wheel building, so the installation with pip would miss this package. I will then add the `src_install` entry now :)
> 
> You can have a separate mamba install call before the pip install, i.e. it's a list so you can just add more things as necessary - I believe a few other mdakits do this (I'll try to find an example later if I get a chance)

Ah, then it should be fine, I will then go to sleep now and take a look tomorrow, since if it is possible to first run the mamba install then it shouldn't be a problem :)

2024-09-04 00:01 UTC, talagayev commented
@IAlibay okay `mdahole2`,  `lipyds` and `openmm-mdanalysis-reporter` all do it the way you mentioned, by git cloning the repository, then installing through `mamba install` and then going into the cloned folder and then using `pip install .` I will see if it works now with `mamba install` and directly afterwards `pip install` from github without the git cloning and `cd` into the folder

2024-09-06 21:12 UTC, orbeckst commented
@talagayev please ping me when you've made progress and think it's ready (i.e., everything installs and passes tests) or if there are questions.

2024-09-10 23:17 UTC, talagayev commented
@orbeckst I think everything is ready and should be now running correctly including the installation with `src_install` and all the pytests :)

2024-09-11 08:51 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +  - mamba install -c conda-forge openmmdl
Ah yes that I can do, I have an environment.yml with all of the necessary packages there, which are required for the pakckage so I can adjust the scr_install to use that :)

As for the 0.0.1 I will check what the reason is behind it finding the 0.0.1 version, eventhough it should be directly the 0.9.2 version

2024-09-11 20:50 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +  - mamba install -c conda-forge openmmdl
@orbeckst I adjusted and added directly all of the packagaes in the yaml file for the `src_install` so it should be fine now :)

As for the 0.0.1 version, it was as a `default_version` in the `pyproject.toml`, which appearantly was the reason why it recognized than that version during the `pip install .` step and did the uninstallation. I think I managed to get now the dynamic version into the `pyproject.toml`

2024-09-12 18:48 UTC, orbeckst requested changes
Please see comments!

(I wrote these days ago but apparently forgot to submit review, sorry for the delay.)

2024-09-12 18:52 UTC, talagayev commented
> Please see comments!
> 
> (I wrote these days ago but apparently forgot to submit review, sorry for the delay.)

will do, all good :)

2024-09-12 18:53 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +    conda install -c conda-forge
adjusted it to mamba

2024-09-12 18:55 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +    mdanalysis>=2.3.0
also a similar case is for `versioningit` and `setuptools` which I have in the `pyproject.toml` so they are installed there in theory, but I thought if I list the remaining packages I can also add them in the `mamba install` step so that all of the packages necessary for the package are present

2024-09-12 18:57 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +#changelog: https://github.com/wolberlab/OpenMMDL/blob/main/CHANGELOG.md
ah yes, had the similar case in the `MDonatello` PR request, somehow I forget that `#changelog` is hashed out

2024-09-12 18:57 UTC, talagayev commented on mdakits/openmmdl/metadata.yaml
> +    mdanalysis>=2.3.0
I will keep for now the `mdanalysis>=2.3.0` to see what the others say if it should be removed or retained :)

2024-09-12 19:50 UTC, orbeckst approved these changes
Thank you for addressing all my comments. Looks ready to me (modulo comments from others).

2024-09-12 19:50 UTC, orbeckst commented on mdakits/openmmdl/metadata.yaml
> +    mdanalysis>=2.3.0
ok

2024-09-12 19:52 UTC, orbeckst commented
@IAlibay I believe your specific comment https://github.com/MDAnalysis/MDAKits/pull/161#pullrequestreview-2278650921 was addressed but would you mind having a quick look through? Thanks.

2024-09-20 00:32 UTC, orbeckst commented
@IAlibay if you want to have a look please do over the next few days, otherwise I'll dismiss.

2024-09-21 20:24 UTC, IAlibay approved these changes
I've made one direct change on the dependencies but otherwise lgtm!

2024-09-21 20:24 UTC, IAlibay commented on mdakits/openmmdl/metadata.yaml
> +    mdanalysis>=2.3.0
I think it makes sense to have MDAnalysis here, in the end this will go in the docs as "this is how you install this".

I have moved pytest things into test_dependencies though, because as far as I'm aware they aren't necessary for the standard operations of the code.

2024-09-21 20:31 UTC, merged

2024-09-22 17:24 UTC, talagayev commented
Nice, thank you @orbeckst and @IAlibay for accepting and helping with this MDAKits entry :)

![possum](https://github.com/user-attachments/assets/62ca9f7b-4640-42f3-ae24-a1e96a76e88e)