MDAKit registration: DomHMM
MDAnalysis/MDAKits pull request #164
Opened 2024-09-06 14:40 UTC by m-a-r-i-u-s

Dear MDAKit Maintainer/Developers,

I would like to register our recent project **DomHMM** as a MDAKit.
**DomHMM** is a package mainly based on the MDAnalysis library to identify lateral heterogeneities (e.g., liquid-ordered domains) in Molecular Dynamics simulations of lipid bilayers. Our tool is easy to use and should cover a wide range of standard simulation setups (i.e., symmetric and asymmetric membranes, membranes including small proteins). However, this is our first open-source project, and if there is something missing or can be improved, we are open for any suggestions. Note, that we have a documentation describing our package: https://domhmm.readthedocs.io/en/latest/?badge=latest, but more details on the method can be found here: https://doi.org/10.1016/bs.mie.2024.03.006.

The package can be found here: https://github.com/BioMemPhys-FAU/domhmm

With regards,
Marius

2024-09-06 21:15 UTC, orbeckst commented
Hello to Erlangen! My undergrad institution :-)

Thank you for your contribution. We'll have a look and work with you. Please be patient with us and ask if anything is unclear.

2024-09-06 21:47 UTC, orbeckst requested changes
This looks already really good: you have tests, docs, maintainers, and the *develop* CI runs successfully.

I would be really good if there were instructions for how to install the **latest release**. At the moment, the CI tests for [latest](https://github.com/MDAnalysis/MDAKits/actions/runs/10740352382/job/29790746080?pr=164) do not install anything and then happily pass. 

But it is really useful for users to know how to install the latest released version (currently your [v1.0.0](https://github.com/BioMemPhys-FAU/domhmm/releases/tag/v1.0.0)) so although we do _require_ it we very much encourage you to provide this information. We'd be happy to help you upgrade your package. For initial suggestions for two different ways see below:


## pypi

Users prefer to be able to just `pip install` your package, so I very much encourage you to put the released version of the package on PyPi — the Python Packaging Guide's [Uploading the distribution archives](https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives) is a concise description of what needs to be done.

Once you've done that, 
- update the `install:` section of the meta.yml file with the appropriate `pip install domhmm` (or similar) command
- update your docs with the installation instructions

## source package

Alternatively, you can have users install from the released archives from https://github.com/BioMemPhys-FAU/domhmm/releases/tag/v1.0.0 or by cloning the repo and switching to the latest release tag.

- include appropriate docs for users
- update the `install:` section with the commands I mention in the review comment (namely, the `git clone latest` where the _latest_ is some of our magic that means for us to find the latest tag on your repo and install it).

2024-09-06 21:47 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +# TEMPLATE MDAKit file
Suggestion: replace any "template" language/comments with something about your package and feel free to delete any instructional comments.

2024-09-06 21:47 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Your package seems to be in good state already. Would you consider adding it to PyPi? It's a straightforward process and it would make it a lot easier for users to install.

Otherwise we can say here
```yaml
install:
 - git clone latest
 - pip install .
```
(I _think_ this should work, asking @IAlibay for confirmation/suggestions.)

2024-09-06 23:05 UTC, m-a-r-i-u-s commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Hi @orbeckst ,
I will tag @yusuferentunc . He is handling the installation issues and will look into adding DomHMM to PyPi.

2024-09-07 10:18 UTC, m-a-r-i-u-s commented on mdakits/domhmm/metadata.yaml
> +# TEMPLATE MDAKit file
I added some more information about the package. Additional information about the installation will be added.

2024-09-10 20:22 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Do you want to try out
```suggestion
install:
 - git clone latest
 - pip install .
```
and see if this runs? This would be a first step. You can immediately replace it with
```
install:
 - pip install domhmm
```
once @yusuferentunc has created the PyPi package.

2024-09-10 20:46 UTC, m-a-r-i-u-s commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
I tried the following sequence of commands:

1. git clone https://github.com/BioMemPhys-FAU/domhmm.git
2. cd domhmm
3. pip install .

And it installed domhmm successfully. Is this the workflow you had in mind?

2024-09-10 21:32 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Sort of, you also want to get the latest release tag, which is 1.0.0 in your case:
```
git clone https://github.com/BioMemPhys-FAU/domhmm.git
cd domhmm
git fetch --tags
git checkout 1.0.0
pip install .
```
but for the meta.yml's install target you don't need the `cd domhmm` or know the latest tage because that's part of the magic of `git clone latest` — which is not really a git command but a special step that we use and parse in a specific way  https://github.com/MDAnalysis/MDAKits/blob/8a04d6ada4eb65d2b7d0ac3527746e9d5444cbbc/utils/mdakit.py#L540-L546 

So for docs you would write something like the above but for the meta.yml you'd use the commands that I wrote in https://github.com/MDAnalysis/MDAKits/pull/164#discussion_r1752675531 .

2024-09-11 12:28 UTC, m-a-r-i-u-s commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
I tried it for python 3.9, 3.10, and 3.12, and I could install domhmm successfully. I only got an error message for python 3.9 regarding pip on my M1 MacBook: "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. "However, if I switch to an intel-based Mac, everything works fine.

2024-09-11 18:52 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Python 3.9 will not even be supported for MDAnalysis 2.8.0 so I think having some issues with the 3.9 and Apple silicon is acceptable.

2024-09-11 18:55 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Hm, sorry, my suggestion did not work — https://github.com/MDAnalysis/MDAKits/actions/runs/10811290602/job/30011929019?pr=164#step:7:19

@IAlibay does `git clone latest` not work with `install:` ?

2024-09-12 01:02 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Given that my original idea did not work, you could have it explicitly install the 1.0.0 with
```yaml
install:
  - mamba install -c conda-forge numpy scipy scitkit-learn hmmlearn networkx
  - pip install https://github.com/BioMemPhys-FAU/domhmm/archive/refs/tags/1.0.0.tar.gz
```
(MDAnalysis will be installed automatically.)

Once you have the pypi package up, you can update this entry in the registry.

By the way, I looked at your dependencies in https://github.com/BioMemPhys-FAU/domhmm/blob/de318b9a3c0cd07eb083d5b6d2c944e7a3f6201f/pyproject.toml#L22-L28 and noticed that you're pinning to fixed versions. I would avoid that unless you have a very good scientific reason because pinned packages can lead to mutually exclusive dependencies and make it very difficult for users to create an environment with their own choice of packages. Instead I would use ranges such as `>=0.3.2` or `>=1.0,<2.0` (you need to look up the exact syntax but you get the idea). 

Alternatively, if you don't want to test the 1.0.0 release here, you can also comment out the `install:` part. It is [an optional entry](https://mdakits.mdanalysis.org/reviewersguide.html#optional-entries) for a MDAKit and so I would approve the registration without it. Users would see a gray banner for "Latest Release" in the registry. You could update your registration once you have the PyPi package available.

2024-09-12 02:16 UTC, IAlibay commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Duplicating what I mentioned on discord: `install` is a specific thing - it indicates "how do I install the packaged version of this code". If the code is only releasing through github, i.e. no package is being distributed, then `src_install` is all you can advertise in the registry, because all that mdakit is offering is source installs.

Please do not hardcode a tag in `install`, that breaks the idea of how the registry should work.

2024-09-12 18:28 UTC, orbeckst commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
The hard-coded tag was meant to be an interim until the pypi package is up.

It sounds to me that the easiest way forward is to **just comment out `install` for now** and update the metadata once you have a pypi package.

(For more discussion on `install` see discord.)

2024-09-12 18:30 UTC, orbeckst requested changes
All you need to do in order for the kit to be registered is to comment out the `install:` step (as you originally had). 

Once you have a PyPi package, you can then update the metadata in a PR.

2024-09-12 20:33 UTC, m-a-r-i-u-s commented on mdakits/domhmm/metadata.yaml
> +#  - pip install MYPROJECT
Thanks @orbeckst and @IAlibay for your input and your suggestions! I commented out `install`, @yusuferentunc is currently looking into the pypi issue. Unfortunately, he will be not in the office until next week, so maybe it can take a few more days. I opened further an [issue](https://github.com/BioMemPhys-FAU/domhmm/issues/53#issue-2523298903) for the versions of our dependencies and I will take a look as soon as possible.

2024-09-12 20:40 UTC, orbeckst approved these changes

2024-09-12 20:41 UTC, merged

2024-09-12 20:42 UTC, orbeckst commented
@m-a-r-i-u-s , your kit is registered, congratulations! 🎉 

Once you have a PyPi package, please open a PR to add the `install` step — you can just quickly edit the metadata file on GitHub.

2024-09-12 20:43 UTC, orbeckst commented
ALso thank you for considering my comment on dependency pinning.

2024-09-12 20:54 UTC, m-a-r-i-u-s commented
@orbeckst Yeah! :)
Thank you very much for your input and this amazing project!