Splitting the tutorial
MDAnalysis/MDAKits pull request #173
Opened 2024-10-11 01:56 UTC by fiona-naughton

Addressing #156 , though I may have got a little carried away in tidying up/adding some other stuff in the process. 

The Making (and Registering) a Kit page is now split over multiple pages (and further split to numbered steps), and the pages have been slightly re-ordered. The basic tutorial content should be largely intact, but I reworded/added some things I felt would improve clarity and make it flow better now it's over multiple pages, particularly at the start of the adding documentation section, and there's a "requirements checklist" that gets updated at the end of each of the tutorial pages.

2024-10-19 02:19 UTC, orbeckst requested changes
This is excellent! It becomes much more digestible and you added a lot of good bridges between existing content.

I found a few typos that need correcting.

I would also prefer *About* (or similar content) to be more prominent. It's important that people understand quickly what MDAKits are.

If you need another page for "Other resources", perhaps make a separate Citations page. Then it's also clear how to cite.

(Not for this PR: We should change the title of the Registry page itself to simply *Registry of MDAKits* and not write out "MDAnalysis Toolkits" — explaining this is the job of the landing page/About page. For the registry title we should just use our "brand name".)

2024-10-19 02:19 UTC, orbeckst commented on docs/source/making-a-kit/guided-example/add-docs.rst
> +   default branch (likely be `main`) are correct.
"be" ?

2024-10-19 02:19 UTC, orbeckst commented on docs/source/making-a-kit/hosting.rst
> +the commands for this in the ``scr_install`` field of your ``metadata.yaml``
src_install

2024-10-19 02:19 UTC, orbeckst commented on docs/source/registering-a-kit/step-by-step.rst
> +MDAKit cookiecutter example.*
Could use a `.. SeeAlso::`.

2024-10-19 02:19 UTC, orbeckst commented on docs/source/index.rst
> +   about
I would leave *About* near the top of the list and also make sure it's linked from the intro text.

What do you need to see if someone sends you to mdakits.mdanalysis.org for "their code" and you don't really know what to with this? Or "just make a MDAKit out of your code".

2024-10-19 02:19 UTC, orbeckst commented on docs/source/maintainingakit.rst
> +   This section is still under construction, and more information will be added
I'd remove the ", and more information will be added soon!". Who knows when content will appear... 

Perhaps encourage contributions or link to discussions, maybe we get enough discussions/solutions so that we can put it here?

2024-10-22 22:19 UTC, orbeckst commented
Just to add: I'd really like to see your update live soon as it's a massive improvement in readability and it would make it so much easier to send people to specific pages for advice.

2024-10-22 22:21 UTC, orbeckst commented on docs/source/making-a-kit/from-cookiecutter.rst
> +of this tutorial is available on YouTube.
Actually, there's an open issue #86 ... so this is not something that needs to be solved in this PR!

2024-10-23 05:28 UTC, fiona-naughton commented on docs/source/making-a-kit/guided-example/make-release.rst
> +The MDAKit cookiecutter uses the
Looks like you're right about migrating to versioningit, thanks - I'll update this.

2024-10-23 06:48 UTC, fiona-naughton commented on docs/source/making-a-kit/from-cookiecutter.rst
> +of this tutorial is available on YouTube.
I've had a go at this, anyway (it didn't seem complicated, so might as well kill two birds with one stone)

2024-10-23 06:48 UTC, fiona-naughton commented
Thanks @orbeckst  - hopefully I've addressed all your comments!

2024-10-23 07:54 UTC, IAlibay approved these changes
This looks good to me, thanks.

2024-10-23 16:08 UTC, orbeckst approved these changes

2024-10-23 16:08 UTC, orbeckst commented
Looks great!!!

2024-10-23 17:15 UTC, merged