Expand the "Maintaining an MDAKit" documentation
MDAnalysis/MDAKits pull request #223
Opened 2024-10-31 10:30 UTC by fiona-naughton

I've added assorted information related to maintaining a kit. This is non-exhaustive so I've kept the "this is under construction" message. 

Information that has been added:
- Instructions for viewing failing tests ( #154 ). ( @lilyminium, I've currently included a gif showing this for lipyds, since that's failing at the moment. I may contrive something later and replace this anyway, but for now let me know if you'd rather I not use lipyds)
- Mention and link to JOSS publication ( #115 ). This is only brief; there is still the potential to show more detail/a specific example.
- Start mentioning some of the things in #114 - I'm aiming to add more details as part of #170, which is in progress.
- Mention the logo templates (and add a legal disclaimer), which are currently only mentioned on the cookiecutter docs

2024-11-10 14:28 UTC, IAlibay requested changes
Thanks @fiona-naughton here are some comments.

2024-11-10 14:28 UTC, IAlibay commented on docs/source/maintainingakit.rst
> +Successfully registering an MDAKit is not the end of the journey! Like a pet, a
I see where you're going here - my 2 cents is that the "like a pet" is maybe a bit too much, but I leave it to you

2024-11-10 14:28 UTC, IAlibay commented on docs/source/maintainingakit.rst
> +``metadata.yaml``) are automatically rerun each week, so that you (and potential
```suggestion
``metadata.yaml``) are automatically rerun twice each week, so that you (and potential 
```

2024-11-11 04:20 UTC, fiona-naughton commented on docs/source/maintaining-a-kit/improving.rst
> +- :ref:`Add a logo <logo>`: Spice up your MDAKit with your very own logo!
fair; I wanted a way to bring it to people's attention that they could have a logo, since it's not mentioned anywhere else (and rule of threes to make this not sound awkward). Perhaps if I added 'you could even...' to make it clearer it comes after the two former things?

2024-11-11 05:03 UTC, fiona-naughton commented on docs/source/maintaining-a-kit/improving.rst
> +Updating the MDAKit's metadata
I don't like splitting things up too much when the sections are this short (makes for a lot of back-and-forth mavigation), but that being said I am planning to add more documentation later that includes details on some of the other above things, and at that stage likely would better to go separate pages.
I'd keep this updating section here since it's generally relevant, but might move the publishing/logo sections

2024-11-11 06:13 UTC, fiona-naughton commented on docs/source/maintaining-a-kit/keep-healthy.rst
> +If an MDAKit fails the weekly CI
Another currently-in-the-works thing I have is a section diving more into CI (and hopefully a glossary, too) - I don't want to end up definitely it separately each time it gets brought up, and in any case I think such a section would be better placed in the making a kit section rather than here. But I could at least add something quick here, if at least an interim till I get other stuff done and up

2024-11-11 06:16 UTC, fiona-naughton commented on docs/source/maintaining-a-kit/keep-healthy.rst
> +Sometimes, this means that things your kit relies on will no longer work.
not sure what you mean, sorry?

2024-11-11 06:18 UTC, fiona-naughton commented on docs/source/maintainingakit.rst
> +Successfully registering an MDAKit is not the end of the journey! Like a pet, a
that's fair - I wasn't actually super happy with this either 😅 but also didn't like how it read jumping straight in - let me think on it again

2024-11-11 06:20 UTC, IAlibay commented on docs/source/maintaining-a-kit/keep-healthy.rst
> +Sometimes, this means that things your kit relies on will no longer work.
"things your kit relies on", the "things" felt a bit unspecific so I was wondering if there was better wording

2024-11-11 06:31 UTC, fiona-naughton commented on docs/source/maintaining-a-kit/keep-healthy.rst
> +Sometimes, this means that things your kit relies on will no longer work.
fair; let me think on that, I'd personally avoid mentioning API though because that's one of those confusing-to-newcomers terms

2024-12-19 20:46 UTC, orbeckst approved these changes
looks great!

2024-12-19 20:52 UTC, orbeckst commented on docs/source/maintaining_a_kit/publishing.rst
> +`relatively simple <https://joss.readthedocs.io/en/latest/submitting.html#submission-process`>_ -
incorrect link syntax
```suggestion
`relatively simple <https://joss.readthedocs.io/en/latest/submitting.html#submission-process>`_ -
```

2024-12-19 20:54 UTC, orbeckst commented
I think all of @IAlibay 's detailed comments have been addressed. I'd be ok with merging to get it out there.

2025-03-26 01:24 UTC, merged