add openmm-mdareporter
MDAnalysis/MDAKits pull request #43
Opened 2023-04-05 13:31 UTC by sef43

PR to start adding OpenMM MDAnalysis reporter to the MDAKits registry as discussed in https://github.com/MDAnalysis/mdanalysis/issues/3401

2023-04-17 20:19 UTC, IAlibay commented
@sef43 - apologies for the delay here, we're in the process of improving our docs for adding mdakits, especially when it comes to adding things so that tests will run properly. We'll come back to this (and other PRs open) once that's done, so that we can point folks to the right steps to getting everything working.

2023-04-19 07:40 UTC, sef43 commented
> @sef43 - apologies for the delay here, we're in the process of improving our docs for adding mdakits, especially when it comes to adding things so that tests will run properly. We'll come back to this (and other PRs open) once that's done, so that we can point folks to the right steps to getting everything working.

No problem, give me a ping when things are ready!

2023-05-25 10:52 UTC, sef43 commented
I've now updated this package to use the cookiecutter template @ianmkenney, it should work with the MDAKits CI

2023-05-25 13:33 UTC, IAlibay requested changes
Thanks @sef43 - a couple of comments, most non-blocking, but it would be good to get these addressed now so that we don't forget to update later

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +documentation_home: https://github.com/sef43/openmm-mdanalysis-reporter
Could you point this directly to the README? (I know propkatraj's entry doesn't right now, but ideally folks shouldn't have to dig around too much)

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +  - mamba install -c conda-forge openmm
Could I ask that you use the jaime shim here as part of your channels? It'd be preferable not to pull down cuda every time.

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +  - mamba install -c conda-forge openmm
same here re: shim

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +  - https://github.com/sef43
if it's not a link to an `AUTHORS` file, this really should be just a list of author names (otherwise the link generation will look a bit odd)

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +  - https://github.com/sef43
Could you use `https://github.com/sef43/openmm-mdanalysis-reporter/blob/main/AUTHORS.md` instead?

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +python_requires: ">=3.7"
Are you sure? Your pyproject.toml states >3.9: https://github.com/sef43/openmm-mdanalysis-reporter/blob/main/pyproject.toml#L19

2023-05-25 13:33 UTC, IAlibay commented on mdakits/openmm-mdareporter/metadata.yaml
> +  - pip install git+https://github.com/sef43/openmm-mdanalysis-reporter
Assuming that this is now non-develop code, would you consider doing a release? Maybe a 0.1 or even a 0.0.1?

2023-05-25 21:40 UTC, sef43 commented
Thanks for review. I have now updated with a 0.1 release and put it on PyPI.

2023-05-25 21:56 UTC, IAlibay approved these changes
lgtm, thanks @sef43 !

2023-05-25 21:56 UTC, merged