Rmsftutorial
MDAnalysis/MDAKits pull request #48
Opened 2023-04-19 18:45 UTC by ianmkenney

RMSF tutorial documentation.

2023-05-02 19:24 UTC, ianmkenney commented
@IAlibay mind taking a look? I think this is nearly done.

2023-05-03 17:27 UTC, IAlibay commented
@fiona-naughton can you review this too please?

2023-05-03 17:42 UTC, IAlibay submitted a review, later dismissed

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +For this reason, we make use of the MDAKit cookiecutter in this example.
"To aid in this process"

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +The MDAKits cookiecutter template can be used to rapidly develop a FAIR-compliant MDAKit by generating placeholder code for documentation, testing, and installation.
we should link to the cookiecutter project itself - make it clear that it'll build a full repository for us.

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +Starting from an environment with Python 3.8+ and the `cookiecutter tool <https://cookiecutter.readthedocs.io/en/stable/>`_, the MDAKit template is generated using
This should be 3.9+ now (we've ditched 3.8 as of April 14th)

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +#. LICENSE -- defaults to GLPv2
is it GPLv2 or GPLv2+ ? (we should be defaulting to the latter)

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +Inserting our code
"Adding our code to the newly created repository"? (sorry inserting our code just sounds off)

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
> +In the event that a kit no longer passes its tests, an issue in MDAnalysis/MDAKits is automatically raised while notifying the maintainers indicated in the `metadata.yaml` file.
We should expand this a little bit - essentially we need to say that a) folks are expected to fix things once the issue is raised, b) once fixed the issue will self-close at the next run of CI.

2023-05-03 17:42 UTC, IAlibay commented on docs/source/makingakit.rst
This isn't showing up in the docs properly - has it been added to the TOC?

2023-05-03 17:52 UTC, ianmkenney commented on docs/source/makingakit.rst
> +#. Tests and continuous integration are present
It's listed as a required feature in the whitepaper

2023-05-03 17:53 UTC, ianmkenney commented on docs/source/makingakit.rst
> +#. Tests and continuous integration are present
![image](https://user-images.githubusercontent.com/7085164/236002715-332bb7f6-cdb8-4d0a-a44f-945e42e81c1a.png)

2023-05-03 18:02 UTC, ianmkenney commented on docs/source/makingakit.rst
> +#. LICENSE -- defaults to GLPv2
you're right, it's v2+

2023-05-03 18:27 UTC, ianmkenney commented on docs/source/makingakit.rst
I don't see what you're referring to, I see it in the side bar and in the table of contents on index

2023-05-08 21:12 UTC, orbeckst commented on docs/source/makingakit.rst
> +#. Tests and continuous integration are present
Just because Ian and I discussed this issue I'll quickly offer my $0.02: If we said it in the white paper then we need to say it here again. (Otherwise we should change the w/p.)

2023-05-10 15:33 UTC, IAlibay commented
Sorry I'm not sure if I'll be able to re-review quickly. @fiona-naughton could you take over here? Feel free to discard my review as necessary.

2023-05-10 15:34 UTC, IAlibay commented on docs/source/makingakit.rst
This is showing up now (wasn't when I looked at it strangely).

2023-05-10 15:36 UTC, IAlibay commented on docs/source/makingakit.rst
> +#. Tests and continuous integration are present
:/ We should probably drop it from the whitepaper - it's not necessary for them to have CI up, just that we can put up CI on their work.

In the short term, let's go with it, we can deal with the whitepaper change later once we get feedback from folks adding their kits.

2023-05-11 17:47 UTC, ianmkenney commented
@fiona-naughton can you take a look at this?

2023-05-12 22:53 UTC, fiona-naughton requested changes
Mostly just spelling fixes, and replacing some instances of ianmkenney to the generic yourusername to be consistent throughout; but otherwise looks good!

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +#. Code is versioned and provides in an accessible version-controlled repository (GitHub, GitLab, Bitbucket, etc.)
```suggestion
#. Code is versioned and provided in an accessible version-controlled repository (GitHub, GitLab, Bitbucket, etc.)
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +analysis class into the ``rmsfkit.py`` file, where the documentation has been
probably worth including the folder (ie rmsfkit/rmsfkit.py)

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	    aligned to a reference structure. The protein also has be whole because
```suggestion
	    aligned to a reference structure. The protein also has to be whole because
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	             numerical overflow or underflow occured
```suggestion
	             numerical overflow or underflow occurred
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +Here we take the `RMSF testing class <https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/analysis/test_rms.py>`_ and update the contents of ``test_rmsfkit.py`` to reflect
again, probably worth having the full path (rmsfkit/tests/test_rmsfkit.py)

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +we need to add it as a dependency in ``devtools/conda-envs/test_env.yaml``.
add a snippet here of the new lines, like for the other changed files below?

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +Up until this point we haven't tested any of the code. Following the the
```suggestion
Up until this point we haven't tested any of the code. Following the 
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +environment using ``conda`` or ``mamba`` (recommended).
might be worth mentioning they need to be back in the main directory for this?

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +configuration as well a premade documentation environment file that is used by
```suggestion
configuration as well as premade documentation environment file that is used by
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	    git clone git@github.com:ianmkenney/rmsfkit.git
```suggestion
	    git clone git@github.com:yourusername/rmsfkit.git
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +If your documentation need citations, you can easily include them using the bibtex format.
```suggestion
If your documentation needs citations, you can easily include them using the bibtex format.
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +Refeshing the RMSF documentation will now show a properly formatted citation using the information in the bibtex file.
```suggestion
Refreshing the RMSF documentation will now show a properly formatted citation using the information in the bibtex file.
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +Log into `Read the Docs <https://readthedocs.org>`_ and navigate to the
```suggestion
Log in to `Read the Docs <https://readthedocs.org>`_ and navigate to the
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +Clicking next will begin the deployment. The immediately starts the build
```suggestion
Clicking next will begin the deployment. This immediately starts the build
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	  - https://github.com/ianmkenney/rmsfkit/blob/main/AUTHORS.md
```suggestion
	  - https://github.com/yourusername/rmsfkit/blob/main/AUTHORS.md
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	  - ianmkenney
```suggestion
	  - yourusername
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	  - git clone https://github.com/ianmkenney/rmsfkit.git
```suggestion
	  - git clone https://github.com/yourusername/rmsfkit.git
```

2023-05-12 22:53 UTC, fiona-naughton commented on docs/source/makingakit.rst
> +	project_home: https://github.com/MDAnalysis/hole2-mdakit
yourusername/rmsfkit

2023-05-12 23:32 UTC, ianmkenney commented
@fiona-naughton Addressed your comments!

2023-05-13 04:41 UTC, fiona-naughton approved these changes
lgtm :)

2023-05-13 17:24 UTC, orbeckst commented
@IAlibay does this look ok from your end? — just asking instead of just dismissing your review.

2023-05-13 17:32 UTC, IAlibay commented
> @IAlibay does this look ok from your end? — just asking instead of just dismissing your review.

Please dismiss! If it's passed review by anyone else it's good to go!

2023-05-13 17:37 UTC, merged