Register solvation-analysis as MDAKit
MDAnalysis/MDAKits pull request #67
Opened 2023-09-13 19:05 UTC by orionarcher

Thanks for the straightfoward tutorial, this was a painless process.

My one question is regarding the `run_tests` command. Where should this command be executed from? I've written it to be executed from package root. I am a bit confused by the `pytest --pyargs propkatraj.tests` syntax in the example.

2023-09-13 19:28 UTC, orbeckst requested changes
This looks really good, just make `pytest` find the tests.

2023-09-13 19:28 UTC, orbeckst commented on mdakits/solvation-analysis/metadata.yaml
> +  - pytest solvation_analysis/tests
We do not necessarily have your checked-out sources available when the package was conda- or pip-installed. Given that you have the tests included in your package as [solvation_analysis.tests](https://github.com/MDAnalysis/solvation-analysis/tree/main/solvation_analysis/tests) try and have pytest find them using `--pyargs`:
```
pytest -n auto --pyargs solvation_analysis.tests
```
(There are shortcomings to using `--pyargs` in specific cases that @IAlibay knows more about but let's try it for right now. We use it for a bunch of other mdakits.)

2023-09-13 19:30 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - pytest solvation_analysis/tests
If you package your tests then yes, here you should try to use `--pyargs`, the issue with using pyargs is mostly limited to if you're using custom plugins, but those are usually for internal testing use.

2023-09-13 19:33 UTC, IAlibay requested changes

2023-09-13 19:33 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - orionarcher
Do you not have an authors file for this?

2023-09-13 19:33 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - conda install -c conda-forge solvation_analysis
```suggestion
  - mamba install -c conda-forge solvation_analysis
```

2023-09-13 19:33 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - conda install pytest
```suggestion
  - mamba install pytest
```

2023-09-13 20:42 UTC, orionarcher commented on mdakits/solvation-analysis/metadata.yaml
> +  - orionarcher
Not currently, no. There are authors in the JOSS paper and contributors on GitHub.

2023-09-13 20:44 UTC, orionarcher commented on mdakits/solvation-analysis/metadata.yaml
> +  - pytest solvation_analysis/tests
Got it to work and changed in the commit, thanks y'all.

2023-09-13 23:33 UTC, orbeckst requested changes
Tests still failing because of pytest issues but should be a simple fix: either include pytest-xdist or remove `-n auto`.

2023-09-13 23:33 UTC, orbeckst commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install pytest
For the `-n auto` we also need pytest-xdist, I think. 

Try out locally first.

Otherwise great.

2023-09-14 11:33 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install pytest
I pushed the change directly just to double check something, I might keep the block on here for a little bit whilst I work out why MDAnalysis-tui is broken (at least it won't load the right yaml file).

2023-09-14 12:02 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install -c conda-forge solvation_analysis "pandas<2"
See: https://github.com/MDAnalysis/solvation-analysis/issues/93

Ideally if you can either pin your recipees or fix the bug & do a release that would be great, we probably can't have the pandas pin in the install tagline.

2023-09-18 16:56 UTC, orbeckst commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install -c conda-forge solvation_analysis "pandas<2"
@orionarcher please review
- updates in the Python package: PR https://github.com/MDAnalysis/solvation-analysis/pull/92
- update to the conda recipe: https://github.com/conda-forge/solvation_analysis-feedstock/pull/8
Then we can remove the pin here and get this done.

2023-09-18 17:17 UTC, orbeckst commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install -c conda-forge solvation_analysis "pandas<2"
Once the other PRs have been addressed, we remove the pin from here
```suggestion
  - mamba install -c conda-forge solvation_analysis
```
I hope that the conda-forge PR is reviewed in time so that cf can build an updated package before our Thu 9/21 deadline.

2023-09-19 10:28 UTC, IAlibay commented on mdakits/solvation-analysis/metadata.yaml
> +  - mamba install -c conda-forge solvation_analysis "pandas<2"
```suggestion
  - mamba install -c conda-forge solvation_analysis
```

2023-09-19 10:30 UTC, IAlibay approved these changes
Assuming CI passes, lgtm!

2023-09-19 10:36 UTC, IAlibay commented
@orbeckst Since everything has now been addressed I'm going to discard your review and merge (that way we can quickly tell if anything will fall apart on deployment).

2023-09-19 10:36 UTC, merged

2023-09-19 10:54 UTC, orbeckst reviewed
LGTM