improving adding a kit docs
MDAnalysis/MDAKits pull request #81
Opened 2023-09-22 00:29 UTC by orbeckst

- updated example with new template
- expanded explanation of progress
- close #80

2023-09-22 07:47 UTC, IAlibay requested changes
Thanks @orbeckst - couple of things

2023-09-22 07:47 UTC, IAlibay commented on docs/source/about.rst
> +#. Minimal documentation is provided
Do we need extra information here? like "tell us how to install and use your code"

2023-09-22 07:47 UTC, IAlibay commented on docs/source/about.rst
> +#. Code in the package uses the MDAnalysis library
```suggestion
#. The code in the package uses the MDAnalysis library
```

2023-09-22 07:47 UTC, IAlibay commented on docs/source/about.rst
> +#. Code is versioned and provided in an accessible version-controlled repository (GitHub, GitLab, Bitbucket, etc.)
```suggestion
#. The code is versioned and provided in an accessible version-controlled repository (GitHub, GitLab, Bitbucket, etc.)
```

2023-09-22 07:47 UTC, IAlibay commented on docs/source/about.rst
> +#. Tests and continuous integration are present
```suggestion
#. At least minimal regression tests and continuous integration are present
```

2023-09-22 07:47 UTC, IAlibay commented on docs/source/about.rst
> +#. Code is installable as a standard package
```suggestion
#. The code is installable as a standard package
```

I'm putting a bunch of "the" here because it doesn't feel super easy to read when it's "Code does X", feel free to ignore though might just be a stylistic thing.

2023-09-22 07:47 UTC, IAlibay commented on docs/source/add.rst
> +   process is to engage in a conversation with the MDAnalysis team so please be
I don't think we need to go this far as to ask folks to be responsive. I think it's ok if we just say that it's a conversation and it won't be merged until all the relevant questions have been answered?

2023-09-22 14:59 UTC, lilyminium commented on docs/source/add.rst
> +   The `MDAKit registry`_ is still in its infancy, we expect that the way in
```suggestion
   The `MDAKit registry`_ is still in its initial stages. We expect that the way in
```

2023-09-22 15:00 UTC, lilyminium commented on docs/source/add.rst
> +   username or the organization that you're part off.
```suggestion
   username or the organization that you're part of.
```

2023-09-22 15:00 UTC, lilyminium commented on docs/source/add.rst
> +   The name of the Python package, it describes is how you import it in Python
```suggestion
   The name of the Python package. It describes how you import it in Python
```

2023-09-22 15:00 UTC, lilyminium commented on docs/source/add.rst
> +   code.
```suggestion
   code, i.e. it is used in ``import MYPACKAGE``.
```

2023-09-22 15:02 UTC, lilyminium commented on docs/source/add.rst
> +   changelog: https://github.com/MYNAME/MYPROJECT/blob/main/CHANGES
```suggestion
   changelog: https://github.com/MYNAME/MYPROJECT/blob/main/CHANGELOG.md
```

That is what is used in the cookiecutter

2023-09-22 15:03 UTC, lilyminium commented on docs/source/add.rst
> +   development_status: Productions/Stable
```suggestion
   development_status: Production/Stable
```

2023-09-22 15:08 UTC, lilyminium commented
Generally LGTM to me @orbeckst! I took the liberty of committing my and Irfan's minor grammatical or stylistic nitpicks to save any extra effort on those -- I've left open any comment that's a bit more meaningful.

2023-09-22 15:12 UTC, IAlibay requested changes

2023-09-22 15:12 UTC, IAlibay commented on docs/source/add.rst
> +
We should add a 8. here where we mention about checks, failures, and updates - i.e. it is their responsibility to update things as necessary.

2023-09-22 15:12 UTC, IAlibay commented on docs/source/add.rst
> +   The name of your project. This is name of your repository. In the template we
```suggestion
   The name of your project. This is the name of your repository. In the template we
```

2023-09-22 15:12 UTC, IAlibay commented on docs/source/add.rst
> +   assume that this is also the PyPi/conda package name but you can make them
This needs checking, I'm not sure it's true.

2023-09-22 15:21 UTC, IAlibay reviewed
Couple more things

2023-09-22 15:21 UTC, IAlibay commented on docs/source/add.rst
> +   ## Here we use the simple PyPi installation:
```suggestion
   ## Here we use a simple PyPi installation:
```

2023-09-22 15:21 UTC, IAlibay commented on docs/source/add.rst
> +   ## First use `git clone latest` to either clone the top commit for "develop" runs or check out
```suggestion
   ## First use `git clone latest` to either clone the top commit for "development code" checks or check out
```

2023-09-22 15:21 UTC, IAlibay commented on docs/source/add.rst
> +     - pytest --pyargs MYPACKAGE.tests
You shouldn't need to have the `.tests` here? I need to double check but package test discovery should work.

2023-09-22 15:21 UTC, IAlibay commented on docs/source/add.rst
> +   ## See https://pypi.org/classifiers/ for development status classifiers.
We should do the same for the license classifier.

2023-09-22 21:59 UTC, orbeckst commented on docs/source/about.rst
> +#. Tests and continuous integration are present
adding to about and makingakit

2023-09-22 22:01 UTC, orbeckst commented on docs/source/about.rst
> +#. Minimal documentation is provided
yes, adding

2023-09-22 22:20 UTC, orbeckst commented on docs/source/add.rst
> +
added ... please have a look in a moment

2023-09-22 22:22 UTC, orbeckst commented on docs/source/add.rst
> +   assume that this is also the PyPi/conda package name but you can make them
ok, rephrased 

   The name of your project. This is the name of your repository. In the template we
   also use it as the PyPi/conda package name.

2023-09-22 22:29 UTC, orbeckst commented on docs/source/add.rst
> +     - pytest --pyargs MYPACKAGE.tests
ok, removing .tests

2023-09-22 22:33 UTC, orbeckst commented on docs/source/add.rst
> +   ## See https://pypi.org/classifiers/ for development status classifiers.
The example    
```yaml
license: GPL-2.0-or-later
```
does not agree with 
```
License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
```
from https://pypi.org/classifiers/

Given that _we_ do not seem to be following the trove classifiers I won't add a specific link. That seems to be an "raise an issue to decide what we want to use".

2023-09-22 22:36 UTC, IAlibay commented on docs/source/add.rst
> +   ## See https://pypi.org/classifiers/ for development status classifiers.
I think we're using the conda-forge definition of licenses, let me dig that up.

2023-09-22 22:38 UTC, IAlibay commented on docs/source/add.rst
> +   ## See https://pypi.org/classifiers/ for development status classifiers.
Here you go: https://spdx.org/licenses/

That's what we should be using in my opinion. It's concise and (assuming I ever get the time) we should be able to do a pydantic validator that checks against that the spdx list.

2023-09-22 22:43 UTC, IAlibay commented on docs/source/add.rst
> +     - pytest --pyargs MYPACKAGE.tests
Can confirm the auto discovery works using our favourite new mdakit (`solvation_analysis`).

2023-09-22 22:51 UTC, IAlibay commented on docs/source/add.rst
> +   assume that this is also the PyPi/conda package name but you can make them
So I double checked here and you're right - the conda/pip install is freeform so `package_name` doesn't get injected.

The only place where `package_name` is a hard requirement is for codecov, it's a piece of code that currently doesn't work but eventually we'll need up and running (for the badges).

2023-09-22 23:00 UTC, IAlibay commented
Just adding a reminder here that we should transplant any changes made to the docs involving the template back to the actual template itself.

2023-09-22 23:14 UTC, orbeckst commented
> Just adding a reminder here that we should transplant any changes made to the docs involving the template back to the actual template itself.

Yes, I was considering verbatim inclusion but then that didn't quite work with how I wanted some comments removed.

2023-09-22 23:21 UTC, orbeckst commented
I updated template/metadata.yaml. I wasn't 100% sure if I should be doing because the older version gets used in the tutorials. On the other hand, sooner or later we have to do it anyway, https://mdakits.mdanalysis.org/makingakit.html#submitting-the-kit-to-the-registry does _not_ show the template, and the upcoming video tutorial speeds through it quickly (thus indicating more the concept of using the template than having the detailed version). So overall, I'd update now (it's only comments).

2023-09-22 23:24 UTC, orbeckst commented on docs/source/add.rst
> +   ## See https://pypi.org/classifiers/ for development status classifiers.
thanks, added

2023-09-22 23:25 UTC, IAlibay commented
> I updated template/metadata.yaml. I wasn't 100% sure if I should be doing because the older version gets used in the tutorials. On the other hand, sooner or later we have to do it anyway, https://mdakits.mdanalysis.org/makingakit.html#submitting-the-kit-to-the-registry does _not_ show the template, and the upcoming video tutorial speeds through it quickly (thus indicating more the concept of using the template than having the detailed version). So overall, I'd update now (it's only comments).

Yeah I'm not really worried about the video being out of date - it's meant to just give you an idea of what to do / where to look for things.

2023-09-22 23:28 UTC, orbeckst commented on docs/source/add.rst
> +   assume that this is also the PyPi/conda package name but you can make them
Then let's leave it as the more restrictive phrasing for right now.

2023-09-22 23:28 UTC, orbeckst commented on docs/source/add.rst
> +   process is to engage in a conversation with the MDAnalysis team so please be
changed

2023-09-22 23:31 UTC, orbeckst commented on docs/source/add.rst
> +Specification of the ``metadata.yaml`` file
@IAlibay I added this preliminary specification section — mainly so that we can link to the anchor and update later. 

I found that I was piling specs into the "template" section that are actually better described stand-alone. Eventually we can document all entries in this section independent from the template but let's wait until the dust has settled. For right now, I am happy with using the template/metadata.yaml as ground truth.

2023-09-23 12:03 UTC, IAlibay reviewed
Thanks for all the work here @orbeckst - couple of things (I'll merge anything I think is just a minor change) and then I think we're good to go!

P.S. For clout: this review was made from the most Western point in continental Europe!

2023-09-23 12:03 UTC, IAlibay commented on docs/source/add.rst
> +   and some of the optional entries may become required.
```suggestion
   with new optional and required entries. The MDAKits team will assist developers with migrations should they become necessary.
```

2023-09-23 13:44 UTC, lilyminium commented on docs/source/add.rst
> +   information as possible.
```suggestion
   information as possible. Some aspects of the registry checks may not work if these details are missing.
```

Small typo here -- just modifying @IAlibay's suggestion

2023-09-24 04:56 UTC, orbeckst commented
I may be able to work on some of this tomorrow at the airport/plane but if not, please go ahead with whatever seems reasonable.

2023-09-24 06:51 UTC, IAlibay commented
@orbeckst I don't think there's anything really "controversial" left to tackle here - I'm going to go ahead and commit the rest of my suggestions and merge. That way we can get this and the website PR out.

If there's any changes made that you dislike we can always go back and fix it post merge.

2023-09-24 09:12 UTC, merged