WIP: Making a kit from an existing package
MDAnalysis/MDAKits pull request #93
Opened 2023-11-01 21:52 UTC by ianmkenney

Adding documentation for creating an MDAKit from an existing package.

2023-11-04 05:51 UTC, IAlibay commented
@ianmkenney let me know when you want me to review this

2023-11-06 20:18 UTC, orbeckst requested changes
I like the idea of coming at the problem of creating a *registered* MDAKit from a more generic angle and giving hints about licenses etc. I am missing some concrete examples, though. We don't need a tutorial with a fixed case study. But some semi-generic lines of code that we typically see in the registry. Have a look at what we currently have in the meta.yamls and perhaps an obvious pattern emerges. 

Ultimately, I think *this section should prepare a developer to fill in the metadata.yml file* (see https://mdakits.mdanalysis.org/add.html#template-metadata-yaml-file ); look at the comments in the file on the page as they are currently our primary documentation ( :-( ). If you could expand on what's there then that would be really helpful. If you have some examples for what's expected (or worked elsewhere) then that would also show devs what to shoot for.

2023-11-06 20:18 UTC, orbeckst commented on docs/source/makingakit.rst
> +Futher improvements to your testing proceedure may include automatically running the tests on pushing to your remote repositories (see `GitHub Actions <https://github.com/features/actions>`_).
I'd like to see here (and elsewhere) some concrete examples, i.e., the "typical" code that would go into the metadata.yml file.

2023-11-08 02:43 UTC, orbeckst commented on docs/source/makingakit.rst
> +trimmed for the sake of brevity. Documentation is written in `reStructuredText <https://docutils.sourceforge.io/rst.html>`__
Weird, reST should work with a single underscore (see [sphinx: hyperlinks](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links)). You could make it a named link. 

Have you seen any documentation that states that double-underscore links are supported or even needed?

2023-11-15 05:26 UTC, orbeckst requested changes
Some change requests (see comments) and please spell-check. Examples are good and tone/level of expertise is appropriate.

2023-11-15 05:26 UTC, orbeckst commented on docs/source/makingakit.rst
> +The primary concern is ensuring that the core MDAKit requirements are met, as listed at the top of this document.
link so that one can jump to the requirements

2023-11-15 05:26 UTC, orbeckst commented on docs/source/makingakit.rst
> +Take time to consider how you would like to license your project.
add a link to choosealicense to help them

2023-11-15 05:26 UTC, orbeckst commented on docs/source/makingakit.rst
> +Futher improvements to your testing proceedure may include automatically running the tests on pushing to your remote repositories (see `GitHub Actions <https://github.com/features/actions>`_).
Use the word "continuous integration (CI)" somewhere so that people know what we're talking about when we mention it. The tone and level of the existing text is good, though.

2023-11-15 05:26 UTC, orbeckst commented on docs/source/makingakit.rst
> +When submitting an MDAKit to the registry, you can include the instructions for running the tests in the required ``metadata.yaml`` file (see a full example in the `registration <registration>`__ sec
Not "can" but "do", see #95

2023-11-15 05:26 UTC, orbeckst commented on docs/source/makingakit.rst
> +For this reason, if your code is not already hosted in an accessible version controlled repository, hosting on `GitHub <https://github.com>`_ is recommended, although other services such as `BitBucke
add here explanation of the `source_install` entry, see #98

2023-11-18 19:23 UTC, orbeckst approved these changes
Thanks @ianmkenney , looking good.

I have some minor suggestions and a broader question, but nothing that would actually block this PR.

2023-11-18 19:23 UTC, orbeckst commented on docs/source/add.rst
> +   :lines: 1-2,13-
nice!

2023-11-18 19:23 UTC, orbeckst commented on docs/source/makingakit.rst
> +The primary concern is ensuring that the core MDAKit :ref:`requirements<requirements>` are met, as listed at the top of this document.
This ref works; just IIRC the sphinx docs say somewhere "space between text and link name", i.e., `:ref: requirements  <requirements>`. Come to think, if title and link name are the same, then just
```reST
:ref:`requirements`
```
_should_ work. (But test!)

2023-11-18 19:23 UTC, orbeckst commented on docs/source/makingakit.rst
> +With publicly accessible code, users are not required to get go through intermediate packaging services such as the Python Package Index or conda-forge, although having your code available through th
"to get go through" — ?

omit "get"??

2023-11-18 19:23 UTC, orbeckst commented on docs/source/makingakit.rst
> +	  - pytest -v tests/
As written here, this is a safe bet, where everything is explicit.

The docs in the meta.yml file indicate that one can short-cut:
```yaml
# For example, if the tests are in the repository at the top level under `./tests`:
## First use `git clone latest` to either clone the top commit for "development code" checks or check out
## the latest tag for "latest release" checks. Then then run pytest:
##    - git clone latest
##    - pytest -v ./tests
```

What are the pre-requisites for `git clone latest` working properly, @IAlibay ? Does it depend on `src_install` being defined? (I think this is effectively related to #98 )

For this PR I am ok with having the generic instructions. Later (as part of #98 possibly) we should rethink the docs.

2023-11-19 17:55 UTC, IAlibay commented on docs/source/makingakit.rst
> +	  - pytest -v tests/
`git clone latest` depends on `project_home` (which the more I think probably should have been called `src_home`).

2023-11-19 18:22 UTC, IAlibay requested changes
Thanks for this @ianmkenney, looks great!

I've left a couple of comments for some changes, with one of them being a blocker (@orbeckst's suggestion to switch to `git clone latest`).

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +Your license needs to be compatible with the GPLv2+ license currently used by MDAnalysis.
```suggestion
Your license needs to be compatible with the GPLv2+ license currently used by MDAnalysis, in addition to the licenses of any other packages your mdakit depends on.
```
Maybe not the best worded suggestion - essentially "don't just look at MDA" (this is the indirect "addressing Apache 2.0" comment)

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +Take time to consider how you would like to `license your project <https://choosealicense.com/>`_.
I've always found choose a license to be a bit opiniated in the way it thinks about licenses.

How about just throwing a couple of resources here to avoid us endorsing anything specific?

```suggestion
Take time to consider how you would like to license your project. Further information on open source licensing can be found from sources such as;  `choose a license <https://choosealicense.com/>`_, `tl;dr Legal <https://tldrlegal.com/>`_, the `Open Source Initiative <https://opensource.org/osd>`_, and the `Software Sustainability Insitute <https://www.software.ac.uk/resources/guides/choosing-open-source-licence>`_.
```

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +With publicly accessible code, users are not required to get go through intermediate packaging services such as the Python Package Index or conda-forge, although having your code available through th
```suggestion
The registry does not require that your code be available through packaging repositories such as the Python Package Index or conda-forge, although having your code available through these services is highly encouraged.
```
Slight rewording, please ignore if you don't like it - "intermediate packaging services" felt like a bit on the technical side of things.

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +Using a documentation hosting service such as `Read the Docs <https://readthedocs.org>`_ or `GitHub Pages <https://pages.github.com/>`_ makes public access to your generated documentation automatic.
@fiona-naughton these sections might be good entry points for further guides, i.e. this can eventually be switched to "see our guide on building docs for mdakits here".

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +These tests are not just useful for when you make changes to your code, but also when using your code with newer versions of MDAnalysis/Python.
```suggestion
These tests are not just useful for when you make changes to your code, but also when any package dependencies (e.g. MDAnalysis, NumPy, and Python) change.
```

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +Basic tests can be written with a variety of packages, such as the `unittest package <https://docs.python.org/3/library/unittest.html#module-unittest>`_ or the `pytest package <https://docs.pytest.or
Should we say that we recommend the latter?

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +	  - git clone https://github.com/MYGITHUB/MYPACKAGE --depth=1
I'm going to put a change request here - this should either use "git clone latest" or "pip/conda install".

2023-11-19 18:22 UTC, IAlibay commented on docs/source/makingakit.rst
> +	  - git clone https://github.com/MYGITHUB/MYPACKAGE --depth=1
### Why not a regular git clone command?

This will break when running "latest" tests if things have change on the head branch of your repo. We've seen issues with this in practice.

### Should we just encourage pip / conda install instead?

Overall getting folks to package their tests would be easier - git clone latest is a not so amazing workaround (it makes assumptions on using the latest version tag). That being said we'd then need to tell folks about packaging their tests, which is a headache in its own rights.

2023-11-21 22:24 UTC, orbeckst commented on docs/source/makingakit.rst
> +Basic tests can be written with a variety of packages, such as the `unittest package <https://docs.python.org/3/library/unittest.html#module-unittest>`_ or the `pytest package <https://docs.pytest.or
I would want to write 
> "If you don't have settled on a testing framework yet then choose pytest but if you use something else already then that's totally cool because the most important thing is that you _have_ tests." 

but that's very wordy and might just distract.

I am happy to leave it neutral but if one of you has a strong opinion here then we can put it in.

2023-11-21 22:50 UTC, ianmkenney commented on docs/source/makingakit.rst
> +Basic tests can be written with a variety of packages, such as the `unittest package <https://docs.python.org/3/library/unittest.html#module-unittest>`_ or the `pytest package <https://docs.pytest.or
I don't have a strong opinion either way. Whichever framework speaks to the authors is the one they should choose as far as I'm concerned.

2023-11-28 16:49 UTC, IAlibay approved these changes
Thanks @ianmkenney, sorry about the delayed review!

2023-11-28 16:49 UTC, merged